version: "3.9"

services:
  kumkoom-production-web-app:
    container_name: kumkoom-production-web-portal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NITRO_PORT: 3000
      NITRO_HOST: 0.0.0.0
    restart: unless-stopped
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge
