version: "3.8"
services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    image: kumkoom-production-web-portal:latest
    container_name: kumkoom-production-web-portal
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # - NUXT_PUBLIC_API_URL=https://api.example.com
    restart: unless-stopped
    # production ไม่ควร mount source โดยตรง (เอาไว้ dev เท่านั้น)
    # volumes:
    #   - ./:/app:ro
